name: Build tpex-capi

on:
  workflow_run: 
    workflows: ["Run unit tests"]
    # Include tags
    branches: ["master", 'v*.*.*']

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    outputs:
      release_built: ${{ steps.set-output.outputs.release_built }}
    steps:
    - uses: actions/checkout@v4
    - name: Build binaries in release mode
      run: cargo build --profile release --package tpex-capi
    - name: Move binaries to a nice folder
      run: mkdir /tmp/tpex-capi && cp target/release/libtpex_capi.so tpex-capi/tpex-capi.h /tmp/tpex-capi
    - name: Upload release artifact
      uses: actions/upload-artifact@v4
      with:
        name: tpex-capi
        path: /tmp/tpex-capi
