name: Run unit tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      release_built: ${{ steps.set-output.outputs.release_built }}
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: cargo test --features="client, server"
